### PR TITLE
Add application/json Content-Type

### PR DESCRIPTION
**Pull request by conblem**
I am working on a clone of [acme-dns ](https://github.com/joohoi/acme-dns)and my application really cares that the correct Content-Type header is set.

### CODE REVIEW

**Comment by mholt** [comment]
I guess this is fine :) I don't use acmedns so I'll wait to see if... hmm... quite possibly the original author of this repo doesn't have an account anymore.

Ok, merging!

**Comment by sankirta** [comment]
@mholt I do have an account and I still occasionally check out libdns/acmedns and caddy-dns/libdns to see what’s up. Though I also don’t really use it these days.

In any case, thanks for merging. :)

**Comment by sankirta** [comment]
Ah, I guess I pushed my initial commits with an email that’s not associated with my GitHub account, that’s why the commit history doesn’t point to my account.

**Comment by mholt** [comment]
@vbsd Ah, ok. I was wondering why I couldn't click, lol. Sorry about that. Thanks for chiming in! :)

**Pull request merged**
